name: Feature request
description: Suggest an improvement
title: "[Feature]: "
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem to solve
      description: What use case or limitation would this address?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
    validations:
      required: true
